version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo-data:/data/db

  chat-app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SESSION_SECRET: ${SESSION_SECRET}
      PORT: ${PORT}
    depends_on:
      - mongo

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate --url http://chat-app:3000 run --token $TUNNEL_TOKEN
    depends_on:
      - chat-app

volumes:
  mongo-data: